import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import {PGlite} from '@electric-sql/pglite';

test('calendar blocks other weekdays and reserved dates, and the announcement hides without available balance',()=>{
 const source=fs.readFileSync('assets/js/dashboard.js','utf8');
 const nodes=new Map();
 const context={Date,APP:{identity:{hasPersonal:true},daysOffAvailable:2,daysOffRequests:[],daysOffOccupied:[{inicio:'2026-10-09',fin:'2026-10-09'}]},
  $:id=>{if(!nodes.has(id))nodes.set(id,{});return nodes.get(id);}};
 vm.createContext(context);
 vm.runInContext(source.slice(source.indexOf('function dayOffDateAllowed('),source.indexOf('function renderRequestCalendar(')),context);
 vm.runInContext(source.slice(source.indexOf('function renderDaysOffAnnouncement('),source.indexOf('function renderPersonalRequests(')),context);
 assert.equal(context.dayOffDateAllowed('2026-10-06'),true);
 assert.equal(context.dayOffDateAllowed('2026-10-07'),true);
 assert.equal(context.dayOffDateAllowed('2026-10-08'),true);
 assert.equal(context.dayOffDateAllowed('2026-10-05'),false);
 assert.equal(context.dayOffDateAllowed('2026-10-10'),false);
 assert.equal(context.dayOffDateAllowed('2026-10-09'),false);
 assert.equal(context.dayOffDateAllowed('2026-10-16'),true);
 context.renderDaysOffAnnouncement();assert.equal(nodes.get('rail-days-off').hidden,false);
 context.APP.daysOffAvailable=0;context.renderDaysOffAnnouncement();assert.equal(nodes.get('rail-days-off').hidden,true);
 context.APP.daysOffAvailable=null;context.renderDaysOffAnnouncement();assert.equal(nodes.get('rail-days-off').hidden,true);
});

test('embedded leave calendar remains open after selecting a valid date',()=>{
 const source=fs.readFileSync('assets/js/dashboard.js','utf8');
 let renders=0,closed=0,changes=0;
 const input={min:'2026-10-06',max:'2027-04-01',value:'',dispatchEvent(){changes++;}};
 const context={PERSONAL_REQUEST:{dates:[],busy:false},APP:{daysOffAvailable:3},REQUEST_CALENDAR:{targetId:'date'},$:id=>id==='date'?input:{value:'dia_libre'},document:{querySelector:()=>null},requestDateLabel:value=>value,personalRequestMessage(){},
  dayOffDateAllowed:value=>['2026-10-07','2026-10-08','2026-10-09','2026-10-13'].includes(value),Event:class{},syncRequestDateButtons(){},renderRequestCalendar(){renders++;},closeRequestCalendar(){closed++;}};
 vm.runInNewContext(source.slice(source.indexOf('function chooseRequestCalendarDate('),source.indexOf('async function loadPersonalRequests(')),context);
 context.chooseRequestCalendarDate('2026-10-07');
 assert.equal(input.value,'2026-10-07');assert.equal(renders,1);assert.equal(closed,0);
 context.chooseRequestCalendarDate('2026-10-08');context.chooseRequestCalendarDate('2026-10-09');
 assert.equal(context.PERSONAL_REQUEST.dates.length,3);
 context.chooseRequestCalendarDate('2026-10-13');assert.equal(context.PERSONAL_REQUEST.dates.length,3);
 context.chooseRequestCalendarDate('2026-10-08');assert.equal(context.PERSONAL_REQUEST.dates.length,2);
 context.chooseRequestCalendarDate('2026-10-13');assert.equal(context.PERSONAL_REQUEST.dates.length,3);
 context.chooseRequestCalendarDate('2026-10-05');assert.equal(context.PERSONAL_REQUEST.dates.length,3);
});

test('leave approval and counteroffers enforce consent, authorization, reservation and a single debit',async()=>{
 const db=new PGlite();
 try {
  await db.exec(`create role anon;create role authenticated;create schema auth;
   create function auth.uid() returns uuid language sql as $$select '00000000-0000-0000-0000-000000000001'::uuid$$;
   create function dash_colab() returns bigint language sql as $$select coalesce(nullif(current_setting('test.person',true),''),'1')::bigint$$;
   create function asis_rol() returns text language sql as $$select coalesce(nullif(current_setting('test.role',true),''),'miembro')$$;
   create function dash_sesion_vigente() returns boolean language sql as $$select true$$;
   create table asis_colaboradores(id bigint primary key,activo boolean,contrato_inicio date,dias_libres_saldo integer);
   insert into asis_colaboradores values(1,true,current_date-30,1);
   create table asis_solicitudes_personales(id bigint generated always as identity primary key,colaborador_id bigint,tipo text,
     fecha_inicio date,fecha_fin date,detalle text,evidencia_path text,estado text default 'pendiente',respuesta text,creado_at timestamptz default now(),resuelto_por uuid,resuelto_at timestamptz);
   create table asis_admin_eventos(actor_id uuid,accion text,colaborador_id bigint,detalle jsonb);
   create table asis_descansos_presenciales(colaborador_id bigint,fecha date,motivo text,asignado_por uuid,primary key(colaborador_id,fecha));
   create table asis_descansos_auditoria(colaborador_id bigint,fecha date,accion text,motivo text,actor uuid);
   create table asis_dias_libres_movimientos(colaborador_id bigint,cantidad integer,saldo_anterior integer,saldo_resultante integer,motivo text,solicitud_id bigint unique,creado_por uuid);
   create function asis_labora(c asis_colaboradores,f date) returns boolean language sql stable as $$
     select extract(isodow from f)<6 and not exists(select 1 from asis_descansos_presenciales where colaborador_id=c.id and fecha=f)$$;
   create function dash_crear_solicitud(text,date,date,text,text default null) returns jsonb language sql as $$select '{"ok":true,"legacy":true}'::jsonb$$;
   create function dash_solicitudes_personales() returns jsonb language sql as $$select jsonb_build_object('ok',true,'solicitudes',coalesce(jsonb_agg(to_jsonb(s)),'[]'::jsonb)) from asis_solicitudes_personales s where colaborador_id=dash_colab()$$;
   create function dash_admin_solicitudes_personales() returns jsonb language sql as $$select case when asis_rol()='direccion' then jsonb_build_object('ok',true,'solicitudes',coalesce(jsonb_agg(to_jsonb(s)),'[]'::jsonb)) else '{"ok":false}'::jsonb end from asis_solicitudes_personales s$$;
  `);
  const old=fs.readFileSync('supabase/dashboard_18_dias_libres.sql','utf8');
  await db.exec(old.slice(old.indexOf('create or replace function public.asis_descontar_dia_libre_aprobado()'),old.indexOf('revoke all on function public.dash_admin_saldos')));
  const migration=fs.readFileSync('supabase/dashboard_93_solicitar_dias_libres.sql','utf8');
  await db.exec(migration);await db.exec(migration);
  const migration94=fs.readFileSync('supabase/dashboard_94_contraofertas_dias_libres.sql','utf8');
  await db.exec(migration94);await db.exec(migration94);
  const dates=(await db.query(`select f::date::text fecha from generate_series((now() at time zone 'America/Lima')::date+1,(now() at time zone 'America/Lima')::date+20,interval '1 day') f where extract(isodow from f)=2 order by f`)).rows.map(r=>r.fecha);
  const create=async(start,end=start)=>(await db.query("select dash_crear_solicitud('dia_libre',$1,$2,'Mi descanso solicitado') data",[start,end])).rows[0].data;
  const balance=async()=>(await db.query('select dash_mis_dias_libres() data')).rows[0].data;
  assert.equal((await create(dates[0],dates[1])).motivo,'dia_no_permitido');
  const request=await create(dates[0]);assert.equal(request.ok,true);
  assert.equal((await create(dates[0])).motivo,'duplicada');
  assert.equal((await create(dates[1])).motivo,'saldo_insuficiente');
  assert.equal((await balance()).disponibles,0);assert.equal((await balance()).saldo,1);
  await db.query("update asis_solicitudes_personales set estado='rechazada' where id=$1",[request.id]);
  assert.equal((await balance()).disponibles,1);
  const approved=await create(dates[0]);
  await db.query("update asis_solicitudes_personales set estado='aprobada' where id=$1",[approved.id]);
  assert.equal((await balance()).saldo,0);
  assert.equal((await db.query('select * from asis_descansos_presenciales')).rows.length,1);
  assert.equal((await db.query('select * from asis_dias_libres_movimientos')).rows.length,1);
  await db.query("update asis_solicitudes_personales set estado='aprobada' where id=$1",[approved.id]);
  assert.equal((await db.query('select * from asis_dias_libres_movimientos')).rows.length,1);
  assert.equal((await db.query("select has_function_privilege('anon','dash_crear_solicitud(text,date,date,text,text)','execute') allowed")).rows[0].allowed,false);
  assert.equal((await db.query("select has_function_privilege('authenticated','dash_crear_solicitud_base_93(text,date,date,text,text)','execute') allowed")).rows[0].allowed,false);
  await db.exec('update asis_colaboradores set dias_libres_saldo=3');
  const week=(await db.query(`select f::date::text fecha from generate_series((now() at time zone 'America/Lima')::date+21,(now() at time zone 'America/Lima')::date+35,interval '1 day') f where extract(isodow from f) in(3,4) order by f`)).rows.map(r=>r.fecha);
  const wednesday=await create(week[0]);assert.equal(wednesday.ok,true);
  const propose=async(id,date)=>(await db.query("select dash_admin_proponer_dia_libre($1,$2,'Necesitamos reorganizar el equipo') data",[id,date])).rows[0].data;
  const respond=async(id,accept)=>(await db.query('select dash_responder_contraoferta($1,$2) data',[id,accept])).rows[0].data;
  assert.equal((await propose(wednesday.id,week[1])).motivo,'sin_permiso');
  await db.exec("set test.role='direccion'");
  assert.equal((await propose(wednesday.id,week[1])).ok,true);
  assert.equal((await balance()).reservados,1);
  assert.equal((await create(week[1])).motivo,'duplicada');
  assert.equal((await propose(wednesday.id,week[2])).motivo,'contraoferta_pendiente');
  await assert.rejects(db.query("update asis_solicitudes_personales set estado='aprobada' where id=$1",[wednesday.id]),/contraoferta_pendiente/);
  await db.exec("set test.role='miembro';set test.person='2'");
  assert.equal((await respond(wednesday.id,true)).motivo,'no_existe');
  await db.exec("set test.person='1'");
  assert.equal((await respond(wednesday.id,true)).ok,true);
  assert.equal((await respond(wednesday.id,true)).motivo,'no_existe');
  assert.equal((await balance()).saldo,2);
  assert.equal((await db.query('select fecha::text fecha from asis_descansos_presenciales where fecha=$1',[week[1]])).rows.length,1);
  const second=await create(week[2]);assert.equal(second.ok,true);
  await db.exec("set test.role='direccion'");
  assert.equal((await propose(second.id,week[3])).ok,true);
  await db.exec("set test.role='miembro'");
  assert.equal((await respond(second.id,false)).ok,true);
  assert.equal((await balance()).disponibles,2);
  assert.equal((await balance()).saldo,2);
  assert.equal((await db.query("select has_function_privilege('anon','dash_responder_contraoferta(bigint,boolean)','execute') allowed")).rows[0].allowed,false);
  const migration95=fs.readFileSync('supabase/dashboard_95_seleccion_multiple_dias_libres.sql','utf8');
  await db.exec(migration95);await db.exec(migration95);
  await db.exec('update asis_colaboradores set dias_libres_saldo=3');
  const batchDates=(await db.query(`select f::date::text fecha from generate_series(current_date+50,current_date+70,interval '1 day') f where extract(isodow from f) in(2,3,4,5) order by f limit 4`)).rows.map(r=>r.fecha);
  const batch=async(dates)=>(await db.query("select dash_solicitar_dias_libres($1::date[],'Mis días libres') data",[dates])).rows[0].data;
  assert.equal((await batch(batchDates)).motivo,'saldo_insuficiente');
  assert.equal((await batch([batchDates[0],batchDates[0]])).motivo,'fechas');
  assert.equal((await batch([batchDates[0],'2000-01-01'])).motivo,'dia_no_permitido');
  const invalidFuture=(await db.query("select (current_date+90+(7-extract(isodow from current_date+90)::int))::text fecha")).rows[0].fecha;
  assert.equal((await batch([batchDates[0],invalidFuture])).ok,false);
  assert.equal((await balance()).reservados,0); // earlier valid insert rolled back too
  const submitted=await batch(batchDates.slice(0,3));assert.equal(submitted.ok,true);assert.equal(submitted.ids.length,3);
  assert.equal((await balance()).disponibles,0);assert.equal((await balance()).saldo,3);
  assert.equal((await batch([batchDates[3]])).motivo,'saldo_insuficiente');
  await db.exec("alter table asis_colaboradores add column nombre text default 'Persona de prueba',add column area_id bigint;create table asis_areas(id bigint,nombre text);");
  await db.query("update asis_solicitudes_personales set detalle='Solicitud de día libre para '||fecha_inicio::text where id=any($1::bigint[])",[submitted.ids]);
  const migration96=fs.readFileSync('supabase/dashboard_96_solicitudes_agrupadas.sql','utf8');
  await db.exec(migration96);await db.exec(migration96);
  const grouped=async()=>(await db.query('select dash_admin_solicitudes_agrupadas() data')).rows[0].data;
  assert.equal((await grouped()).motivo,'sin_permiso');
  await db.exec("set test.role='direccion'");
  const existing=(await grouped()).solicitudes.filter(item=>submitted.ids.includes(item.id));
  assert.equal(existing.length,3);assert.equal(new Set(existing.map(item=>item.solicitud_grupo)).size,1);
  assert.ok(existing[0].solicitud_grupo);
  await db.query("update asis_solicitudes_personales set estado='aprobada' where id=$1",[submitted.ids[0]]);
  const partial=(await grouped()).solicitudes.filter(item=>submitted.ids.includes(item.id));
  assert.equal(partial.length,3);assert.equal(partial.filter(item=>item.estado==='aprobada').length,1);
  await db.query("update asis_solicitudes_personales set estado='rechazada' where id=any($1::bigint[]) and estado='pendiente'",[submitted.ids]);
  assert.equal((await grouped()).solicitudes.filter(item=>submitted.ids.includes(item.id)).length,0);
  await db.exec('update asis_colaboradores set dias_libres_saldo=3');
  const nextBatch=await batch(batchDates.slice(1,3));assert.equal(nextBatch.ok,true);assert.ok(nextBatch.grupo);
  const saved=(await grouped()).solicitudes.filter(item=>nextBatch.ids.includes(item.id));
  assert.equal(saved.length,2);assert.ok(saved.every(item=>item.solicitud_grupo===nextBatch.grupo));
  assert.equal((await db.query("select has_function_privilege('anon','dash_admin_solicitudes_agrupadas()','execute') allowed")).rows[0].allowed,false);
  await db.exec(`create schema storage;create table storage.objects(bucket_id text,name text);
    create function dash_solicitud_evidencia_en_uso(p_path text) returns boolean language sql stable as $$select exists(select 1 from asis_solicitudes_personales where evidencia_path=p_path)$$;
    insert into storage.objects values('solicitud-evidencias','1/aaaa.jpg'),('solicitud-evidencias','2/bbbb.jpg');
    update asis_colaboradores set dias_libres_saldo=10;
  `);
  const migration97=fs.readFileSync('supabase/dashboard_97_evidencia_dias_libres.sql','utf8');
  await db.exec(migration97);await db.exec(migration97);
  const evidenceDates=(await db.query(`select f::date::text fecha from generate_series(current_date+100,current_date+110,interval '1 day') f where extract(isodow from f) in(2,3,4,5) order by f limit 2`)).rows.map(r=>r.fecha);
  const withEvidence=async(path)=>(await db.query("select dash_solicitar_dias_libres($1::date[],'Solicitud previa adjunta',$2) data",[evidenceDates,path])).rows[0].data;
  assert.equal((await withEvidence(null)).motivo,'evidencia');
  assert.equal((await withEvidence('2/bbbb.jpg')).motivo,'evidencia');
  assert.equal((await withEvidence('1/cccc.jpg')).motivo,'evidencia');
  assert.equal((await create(evidenceDates[0])).motivo,'evidencia');
  const evidenced=await withEvidence('1/aaaa.jpg');assert.equal(evidenced.ok,true);
  assert.equal((await withEvidence('1/aaaa.jpg')).motivo,'evidencia');
  const reviewEvidence=(await grouped()).solicitudes.filter(item=>item.solicitud_grupo===evidenced.grupo);
  assert.equal(reviewEvidence.length,2);assert.equal(reviewEvidence.filter(item=>item.evidencia_path==='1/aaaa.jpg').length,1);
  assert.equal((await db.query("select dash_solicitud_evidencia_en_uso('1/aaaa.jpg') used")).rows[0].used,true);
  assert.equal((await db.query("select has_function_privilege('authenticated','dash_crear_solicitud_base_97(text,date,date,text,text)','execute') allowed")).rows[0].allowed,false);
 } finally {await db.close();}
});
