import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {PGlite} from '@electric-sql/pglite';
const read=p=>fs.readFileSync(p,'utf8');
test('correction invalidates, notifies, authorizes only its owner and resubmits for the original day',async()=>{
 const db=new PGlite();
 try{
 await db.exec(`
 create role anon;create role authenticated;create schema auth;create schema storage;
 create function auth.uid() returns uuid language sql as $$select '00000000-0000-0000-0000-000000000001'::uuid$$;
 create function asis_rol() returns text language sql as $$select current_setting('test.role')$$;
 create function dash_colab() returns bigint language sql as $$select current_setting('test.owner')::bigint$$;
 create function dash_sesion_vigente() returns boolean language sql as $$select current_setting('test.session')::boolean$$;
 create function dash_cierre_hoy() returns jsonb language sql as $$select jsonb_build_object('ok',true,'fecha',current_date)$$;
 set test.role='direccion';set test.owner='1';set test.session='true';
 create table asis_colaboradores(id bigint primary key);insert into asis_colaboradores values(1),(2);
 create table asis_perfiles(id uuid primary key);insert into asis_perfiles values(auth.uid());
 create table asis_asignaciones_diarias(id bigint primary key,titulo text);
 create table asis_registros(colaborador_id bigint,fecha date,salida_at timestamptz);
 insert into asis_registros values(1,'2020-01-01','2020-01-01T18:00:00-05:00');
 create table asis_cierre_config(id int,habilitado boolean,obligatorio_desde date,comparticiones_min int,collage_permitido boolean);
 insert into asis_cierre_config values(1,true,'2019-01-01',2,true);
 create table storage.objects(id uuid default gen_random_uuid(),bucket_id text,name text,metadata jsonb);
 `);
 const tables=read('supabase/dashboard_19_cierre_jornada.sql');
 await db.exec(tables.slice(tables.indexOf('create table if not exists public.asis_entregas_diarias ('),tables.indexOf('create index if not exists asis_carga_permisos_pendientes_idx')));
 await db.exec(`alter table asis_entrega_archivos drop constraint asis_entrega_archivos_orden_check;
 alter table asis_entrega_archivos add check(orden between 1 and 50);
 alter table asis_entregas_diarias add revision_estado text not null default 'pendiente',add revision_nota text,add revisado_at timestamptz,add revisado_por uuid;
 `);
 const reviews=read('supabase/dashboard_21_revision_evidencias.sql');
 await db.exec(reviews.slice(reviews.indexOf('create table if not exists public.asis_entrega_revisiones'),reviews.indexOf('create index if not exists asis_entrega_revisiones_entrega_idx')));
 const notifications=read('supabase/dashboard_41_centro_notificaciones.sql');
 await db.exec(notifications.slice(notifications.indexOf('create table if not exists public.asis_notificaciones'),notifications.indexOf('create index if not exists asis_notificaciones_bandeja_idx')));
 const trigger=read('supabase/dashboard_50_mensajes_direccion_visibles.sql');
 await db.exec(trigger.slice(trigger.indexOf('create or replace function public.dash_notificar_revision_trg()'),trigger.indexOf('create or replace function public.dash_mis_notificaciones_revision(')));
 await db.exec('create trigger review_notify after insert on asis_entrega_revisiones for each row execute function dash_notificar_revision_trg()');
 const migration=read('supabase/dashboard_108_correccion_comparticiones.sql');await db.exec(migration);await db.exec(migration);
 const value=async(sql,args=[])=>(await db.query(sql,args)).rows[0].data;
 const call=async(name,args=[],types=[])=>value('select '+name+'('+args.map((_,i)=>'$'+(i+1)+(types[i]?'::'+types[i]:'')).join(',')+') data',args);
 const first=await value("insert into asis_entregas_diarias(colaborador_id,fecha,requisito) values(1,'2020-01-01','comparticiones') returning id data");
 await db.exec(`insert into asis_entrega_archivos(entrega_id,path,mime,bytes,orden) values(${first},'old.jpg','image/jpeg',100,1);`);
 await db.exec('set role authenticated');
 assert.equal((await call('dash_admin_revisar_entrega',[first,'observada',' '])).motivo,'nota');
 await db.exec("set test.role='visor'");assert.equal((await call('dash_admin_revisar_entrega',[first,'observada','Captura incorrecta'])).motivo,'sin_permiso');
 await db.exec("set test.role='direccion'");
 assert.equal((await call('dash_admin_revisar_entrega',[first,'observada','Falta la captura del grupo.'])).ok,true);
 await db.exec('reset role');
 assert.equal(await value('select estado data from asis_entregas_diarias where id=$1',[first]),'anulado');
 assert.equal(await value('select mensaje data from asis_notificaciones'),'Falta la captura del grupo.');
 assert.equal(await value('select count(*)::int data from asis_entrega_archivos'),1);
 assert.ok(await value('select salida_at data from asis_registros'));
 await db.exec("set role authenticated;set test.role='colaborador';set test.owner='2'");
 assert.equal((await call('dash_mis_correcciones')).correcciones.length,0);
 assert.equal((await call('dash_correccion_permiso',[first,'collage','jpg'])).ok,false);
 assert.equal((await call('dash_confirmar_correccion',[first,'collage',[]],['','','text[]'])).ok,false);
 assert.equal((await call('dash_marcar_correccion_vista',[first])).ok,false);
 await db.exec("set test.owner='1'");
 assert.equal((await call('dash_mis_correcciones')).correcciones[0].vista,false);
 assert.equal((await call('dash_marcar_correccion_vista',[first])).ok,true);
 assert.equal((await call('dash_mis_correcciones')).correcciones[0].vista,true);
 const permit=await call('dash_correccion_permiso',[first,'collage','jpg']);assert.equal(permit.ok,true);assert.match(permit.ruta,/^2020\/01\/01\/1\//);
 assert.equal((await call('dash_confirmar_correccion',[first,'collage',[permit.ruta]],['','','text[]'])).motivo,'archivo_no_verificado');
 await db.exec('reset role');
 await db.query("insert into storage.objects(bucket_id,name,metadata) values('asis-cierre-evidencias',$1,'{\"size\":100,\"mimetype\":\"image/jpeg\"}')",[permit.ruta]);
 await db.exec('set role authenticated');
 assert.equal((await call('dash_confirmar_correccion',[first,'individuales',[permit.ruta]],['','','text[]'])).motivo,'cantidad_comparticiones');
 assert.equal((await call('dash_confirmar_correccion',[first,'collage',['old.jpg']],['','','text[]'])).motivo,'permiso');
 const saved=await call('dash_confirmar_correccion',[first,'collage',[permit.ruta]],['','','text[]']);assert.equal(saved.ok,true);assert.equal(saved.fecha,'2020-01-01');
 assert.equal((await call('dash_mis_correcciones')).correcciones.length,0);
 assert.equal((await call('dash_confirmar_correccion',[first,'collage',[permit.ruta]],['','','text[]'])).motivo,'correccion_resuelta');
 assert.equal((await call('dash_correccion_permiso',[first,'collage','jpg'])).ok,false);
 await db.exec('reset role');
 assert.equal(await value('select revision_estado data from asis_entregas_diarias where id=$1',[saved.entrega]),'pendiente');
 assert.equal(await value('select count(*)::int data from asis_entrega_archivos'),2);
 await db.exec("set test.role='direccion'");
 assert.equal((await call('dash_admin_revisar_entrega',[saved.entrega,'observada','Revisa otra vez'])).ok,true);
 assert.equal((await call('dash_mis_correcciones')).correcciones[0].vista,false);
 await db.exec("set test.session='false'");assert.equal((await call('dash_correccion_permiso',[saved.entrega,'collage','jpg'])).motivo,'sesion');
 await db.exec('set role anon');await assert.rejects(()=>call('dash_mis_correcciones'),/permission denied/);
 }finally{await db.close();}
});
